"""Turn ``phase_boundary.json`` into LaTeX macros the Paper 1 manuscript can use.

Every number in the paper has to come from a re-runnable script rather than a typed
literal, and a number typed into a manuscript is exactly the kind that survives a change
in the solver. So the figures and the prose read from the same JSON: run
``phase_boundary.py`` first, run this, and the manuscript's numbers move with it.

Macro names avoid digits and underscores because TeX control sequences are letters only.

Usage
-----
    python scripts/paper1_numbers.py \
        --report data/paper1/phase_boundary.json \
        --out data/paper1/numbers.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SPREAD_MACRO_SUFFIX = {"0.1": "OneTenth", "0.5": "Half", "1": "Unity", "2": "Double"}


def _sci(value: float, digits: int = 2) -> str:
    """LaTeX scientific notation, for quantities too small to read as decimals."""
    mantissa, exponent = f"{value:.{digits}e}".split("e")
    return rf"{mantissa}\times 10^{{{int(exponent)}}}"


def macros(report: dict) -> dict[str, str]:
    exps = report["exponents"]
    agreement = report["solver_agreement"]
    beta_j = report["phase_boundary"]["beta_j"]
    h_c = report["phase_boundary"]["h_c"]
    alpha = report["alpha_required_per_spread"]

    out = {
        "pbBetaFitted": f"{exps['beta']['fitted']:.4f}",
        "pbGammaFitted": f"{exps['gamma']['fitted']:.4f}",
        "pbDeltaFitted": f"{exps['delta']['fitted']:.4f}",
        "pbBetaError": f"{exps['beta']['error']:.4f}",
        "pbGammaError": f"{exps['gamma']['error']:.4f}",
        "pbDeltaError": f"{exps['delta']['error']:.4f}",
        "pbFitWindow": f"{exps['window']:g}",
        "pbFitPoints": f"{exps['points']:d}",
        "pbSolverAgreement": _sci(agreement["max_abs_difference"]),
        "pbCriticalBetaJ": f"{report['critical_beta_j']:g}",
        "pbBetaJMax": f"{beta_j[-1]:.2f}",
        "pbHcAtMax": f"{h_c[-1]:.5f}",
    }

    for spread, suffix in SPREAD_MACRO_SUFFIX.items():
        if spread in alpha:
            out[f"pbAlphaRequired{suffix}"] = f"{alpha[spread][-1]:.4f}"
    return out


def render(pairs: dict[str, str]) -> str:
    lines = [
        "% Generated by scripts/paper1_numbers.py from phase_boundary.json.",
        "% Do not edit: re-run the solver instead, or the paper and the figures diverge.",
    ]
    lines += [rf"\newcommand{{\{name}}}{{{value}}}" for name, value in sorted(pairs.items())]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    if not args.report.exists():
        print(f"[FAIL] {args.report} not found. Run phase_boundary.py first.", file=sys.stderr)
        return 1

    report = json.loads(args.report.read_text(encoding="utf-8"))
    pairs = macros(report)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(pairs), encoding="utf-8")

    print(f"Wrote {args.out} with {len(pairs)} macros")
    for name, value in sorted(pairs.items()):
        print(f"  \\{name:26s} {value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
