// ============================================================
// roi-activation.ts -- anatomically accurate demo activation
// ============================================================
//
// Lights the REAL HCP MMP1.0 ROI vertex sets that the NAA index is
// computed over (affective-salience vs deliberative-control), instead of
// arbitrary Gaussian blobs. The relative brightness of the two networks
// is set by the NAA value, so the brain visibly shows what the score
// measures. Generated by services/inference/scripts/export_roi_vertices.py.
// ============================================================

const TOTAL_VERTS = 20484;

export interface RoiVertices {
  affective: number[];
  deliberative: number[];
}

let cachedRois: RoiVertices | null = null;

export async function loadRoiVertices(basePath = '/mesh'): Promise<RoiVertices> {
  if (cachedRois) return cachedRois;
  const res = await fetch(`${basePath}/roi_vertices.json`);
  if (!res.ok) {
    throw new Error(`roi_vertices.json fetch failed (${res.status})`);
  }
  cachedRois = (await res.json()) as RoiVertices;
  return cachedRois;
}

/**
 * Build a (20484,) activation vector lighting the affective-salience and
 * deliberative-control ROIs. NAA = A_aff / A_del, so the deliberative mean
 * is held fixed and the affective mean scales with NAA: high NAA lights the
 * affective network brighter, low NAA lights deliberative brighter. After
 * the renderer's robust normalization the dominant network is the one that
 * shows, which is exactly what the score reports.
 */
export function buildRoiActivation(
  rois: RoiVertices,
  naa: number,
  baselineNoise = 0.01,
): Float32Array {
  const data = new Float32Array(TOTAL_VERTS);
  for (let i = 0; i < TOTAL_VERTS; i++) {
    data[i] = Math.random() * baselineNoise;
  }

  const deliberativeValue = 0.6;
  const affectiveValue = Math.max(0, naa) * deliberativeValue;

  for (const vertex of rois.deliberative) {
    if (vertex >= 0 && vertex < TOTAL_VERTS) {
      data[vertex] = deliberativeValue * (0.82 + Math.random() * 0.18);
    }
  }
  for (const vertex of rois.affective) {
    if (vertex >= 0 && vertex < TOTAL_VERTS) {
      data[vertex] = affectiveValue * (0.82 + Math.random() * 0.18);
    }
  }
  return data;
}

export interface ModalityVertices {
  visual: number[];
  auditory: number[];
  language: number[];
}

let cachedModality: ModalityVertices | null = null;

export async function loadModalityVertices(
  basePath = '/mesh',
): Promise<ModalityVertices> {
  if (cachedModality) return cachedModality;
  const res = await fetch(`${basePath}/modality_vertices.json`);
  if (!res.ok) {
    throw new Error(`modality_vertices.json fetch failed (${res.status})`);
  }
  cachedModality = (await res.json()) as ModalityVertices;
  return cachedModality;
}

// === Real fsaverage5 vertex coordinates (for smooth whole-cortex fields) ===

interface LayoutSection {
  name: string;
  offset: number;
  length: number;
}

let cachedCoords: Float32Array | null = null;

/**
 * Load the (20484, 3) fsaverage5 pial vertex coordinates from the combined
 * binary the mesh pipeline already ships. Used to build smooth, anatomically
 * anchored activation fields instead of hard-edged ROI patches.
 */
export async function loadVertexCoords(basePath = '/mesh'): Promise<Float32Array> {
  if (cachedCoords) return cachedCoords;

  const layoutRes = await fetch(`${basePath}/fsaverage5_combined.layout.json`);
  if (!layoutRes.ok) {
    throw new Error(`mesh layout fetch failed (${layoutRes.status})`);
  }
  const layout = (await layoutRes.json()) as { sections: LayoutSection[] };

  const binRes = await fetch(`${basePath}/fsaverage5_combined.bin`);
  if (!binRes.ok) {
    throw new Error(`mesh binary fetch failed (${binRes.status})`);
  }
  const buf = await binRes.arrayBuffer();

  const section = (name: string): Float32Array => {
    const s = layout.sections.find((x) => x.name === name);
    if (!s) throw new Error(`mesh section ${name} missing`);
    return new Float32Array(buf, s.offset, s.length / 4);
  };

  const coords = new Float32Array(TOTAL_VERTS * 3);
  const left = section('left_pial.coords');
  const right = section('right_pial.coords');
  coords.set(left, 0);
  coords.set(right, left.length);
  cachedCoords = coords;
  return coords;
}

interface SeedSet {
  x: number[];
  y: number[];
  z: number[];
  w: number[];
  k: number[]; // 1 / (2 * sigma^2)
}

function pushSeeds(
  set: SeedSet,
  indices: number[],
  coords: Float32Array,
  maxSeeds: number,
  weight: number,
  sigmaMm: number,
): void {
  if (indices.length === 0) return;
  const step = Math.max(1, Math.floor(indices.length / maxSeeds));
  const k = 1 / (2 * sigmaMm * sigmaMm);
  for (let i = 0; i < indices.length; i += step) {
    const v = indices[i];
    if (v < 0 || v >= TOTAL_VERTS) continue;
    set.x.push(coords[v * 3]);
    set.y.push(coords[v * 3 + 1]);
    set.z.push(coords[v * 3 + 2]);
    set.w.push(weight);
    set.k.push(k);
  }
}

/**
 * Build a smooth, dense (20484,) activation field that reads as actual
 * whole-brain activity rather than two hard ROI blobs. Each vertex sums
 * Gaussian contributions from subsampled seed vertices on the real
 * anatomical networks: the affective-salience and deliberative-control
 * networks the NAA measures (NAA scales their relative brightness) plus the
 * visual/auditory/language networks as a softer whole-cortex backdrop. The
 * result is a continuous map, clear at a glance, anchored on real fsaverage5
 * geometry. The live AMD model replaces this with its true (20484,) output
 * through the same render path.
 */
export async function buildDenseActivation(
  naa: number,
  basePath = '/mesh',
): Promise<Float32Array> {
  const [rois, modality, coords] = await Promise.all([
    loadRoiVertices(basePath),
    loadModalityVertices(basePath),
    loadVertexCoords(basePath),
  ]);

  const base = 0.6;
  const affectiveWeight = Math.max(0, naa) * base * 1.05;
  const deliberativeWeight = base;
  const backdropWeight = base * 0.4;

  const seeds: SeedSet = { x: [], y: [], z: [], w: [], k: [] };
  pushSeeds(seeds, rois.affective, coords, 130, affectiveWeight, 10);
  pushSeeds(seeds, rois.deliberative, coords, 110, deliberativeWeight, 10);
  pushSeeds(seeds, modality.visual, coords, 80, backdropWeight, 13);
  pushSeeds(seeds, modality.auditory, coords, 70, backdropWeight, 13);
  pushSeeds(seeds, modality.language, coords, 80, backdropWeight, 13);

  const { x: sx, y: sy, z: sz, w: sw, k: sk } = seeds;
  const seedCount = sx.length;
  const data = new Float32Array(TOTAL_VERTS);
  let peak = 0;

  for (let v = 0; v < TOTAL_VERTS; v++) {
    const vx = coords[v * 3];
    const vy = coords[v * 3 + 1];
    const vz = coords[v * 3 + 2];
    let acc = 0;
    for (let s = 0; s < seedCount; s++) {
      const dx = vx - sx[s];
      const dy = vy - sy[s];
      const dz = vz - sz[s];
      acc += sw[s] * Math.exp(-(dx * dx + dy * dy + dz * dz) * sk[s]);
    }
    acc += Math.random() * 0.01;
    data[v] = acc;
    if (acc > peak) peak = acc;
  }

  if (peak > 0) {
    const scale = 1 / peak;
    for (let v = 0; v < TOTAL_VERTS; v++) data[v] *= scale;
  }
  return data;
}

function lightVertices(vertices: number[], baselineNoise = 0.02): Float32Array {
  const data = new Float32Array(TOTAL_VERTS);
  for (let i = 0; i < TOTAL_VERTS; i++) {
    data[i] = Math.random() * baselineNoise;
  }
  for (const vertex of vertices) {
    if (vertex >= 0 && vertex < TOTAL_VERTS) {
      data[vertex] = 0.85 + Math.random() * 0.15;
    }
  }
  return data;
}

/**
 * Per-modality activation lighting the real networks each modality drives
 * (paper Fig 7): text -> language + prefrontal, audio -> auditory cortex,
 * video -> visual cortex. Returned as the {text, audio, video} triple the
 * multimodal RGB renderer consumes.
 */
export function buildModalityActivation(modality: ModalityVertices): {
  text: Float32Array;
  audio: Float32Array;
  video: Float32Array;
} {
  return {
    text: lightVertices(modality.language),
    audio: lightVertices(modality.auditory),
    video: lightVertices(modality.visual),
  };
}
